#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

# test "" = "$(grep '^Signed-off-by: ' "$1" |
# 	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
# 	echo >&2 Duplicate Signed-off-by lines.
# 	exit 1
# }

# name=$(git config --local --list | grep user.name)
# if [ -n "$name"];then
# 	name=$(git config --global --list | grep user.name)
# 	if [ -n "$name"];then
# 		echo "NULL"

# 	else
# 		name=${name#*=}
# 	fi
# else
# 	name=${name#*=}
# fi

name=`git config --get user.name`
email=`git config --get user.email`
echo "Author:$name"
echo "Email:$email"
commitMsg="$1"
aa=`cat "$commitMsg"`
result=""
userMailPat="bai*"
function checkP {
	local pattern=$1
	local txt=$2
	result=$(echo "$txt" | grep "$pattern")
	return $?
}

function checkEmail {
	checkP $userMailPat $email
	return $?
}

function checkName {
	checkP $userMailPat $name
	return $?
}

function checkMessage {
	checkP $userMailPat $commitMsg
	return $?
}

checkEmail
if [ -n "$result" ]; then
	echo "邮箱 $result 包含敏感信息"
	exit 1
else
	echo "Email Pass"
fi

checkName
if [ -n "$result" ]; then
	echo "名称 $result 包含敏感信息"
	exit 1
else
	echo "Name Pass"
fi

checkMessage
if [ -n "$result" ]; then
	echo "提交信息 $result 中包含敏感信息"
	exit 1
else
	echo "All Pass"
fi


test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}